version: '3'

services:
 webapp:
   build: ./staticWebSite/
   labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.entrypoints=web,websecure"

   deploy:
    replicas: 3

 http-api:
   build: ./HTTP-API/
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
     - "traefik.http.services.api.loadbalancer.sticky.cookie=true"
     - "traefik.http.services.api.loadbalancer.sticky.cookie.name=cookieapi"
     - "traefik.http.routers.api.tls=true"
     - "traefik.http.routers.api.entrypoints=web,websecure"
   deploy:
    replicas: 3

 reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # HTTPS port
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/certificats:/etc/traefik/certificates
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml